apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:latest #hangi imagela çalışacaksın?
          imagePullPolicy: IfNotPresent # bu image'ı deployment podu restart/scale olduğunda nasıl çekecek?
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
          resources:
            requests: # bu deployment podu çalıştırılmadan önce minimum ne kadar kaynak ayıracak?
              cpu: 250m
              memory: 512Mi
            limits: # bu deployment podu çalışırken maksimum ne kadar kaynak kullanabilir?
              cpu: 500m
              memory: 1Gi # limiti aştığında ne olacak? pod restart olur
          readinessProbe: # docker'daki healtcheck'e benzer bir yapı. podun hazır olup olmadığını kontrol eder. hazır değilse service'e trafik gitmez.
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe: # docker'daki healtcheck'e benzer bir yapı. podun canlı olup olmadığını kontrol eder. canlı değilse pod restart olur.
            tcpSocket:
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15